import org.jenkinsci.plugins.pipeline.modeldefinition.Utils

pipeline {
    agent { label 'IOSDEV2' }

    triggers {
        gitlab(
            triggerOnNoteRequest: true
        )
        cron(env.BRANCH_NAME == 'develop' ? '@midnight': '')
    }

    environment {
        KEYCHAIN_PASSWORD     = credentials('KEYCHAIN_PASSWORD')
        MATCH_PASSWORD        = credentials('MATCH_PASSWORD')

        CIBUILD = true
    }
    parameters {
    }

    options {
        ansiColor('xterm')
        copyArtifactPermission('*')
    }

    stages {
        stage('Fastlane cibuild') {
            steps {
                // Actual CI Build, Tests, Demo App
                sh label: 'starting ios test run', script: '''#!/bin/bash -l
                    if [ -f $HOME/.bash_profile ]; then source $HOME/.bash_profile; fi

                    set -ev

                    security -v unlock-keychain -p "${KEYCHAIN_PASSWORD}" ~/Library/Keychains/login.keychain

                    make cibuild
                    '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'artifacts/**,fastlane/test_output/*,DerivedData/Logs/Test/**', excludes: 'artifacts/**/*.xcarchive/**', allowEmptyArchive: true
            junit 'fastlane/test_output/report.junit'
        }
    }
}
