////
Execute `make readme` after editing <project_root>/README.adoc
////
:doctype: book
:testdir: Tests

= Swift-GemPDFKit

++++
<details>
  <summary>Table of Contents</summary>
  <ol>
    <li>
      <a href="#about-the-project">About The Project</a>
       <ul>
        <li><a href="#release-notes">Release Notes</a></li>
      </ul>
    </li>
    <li>
      <a href="#getting-started">Getting Started</a>
      <ul>
        <li><a href="#prerequisites">Prerequisites</a></li>
        <li><a href="#installation">Installation</a></li>
      </ul>
    </li>
    <li><a href="#usage">Usage</a></li>
    <li><a href="#license">License</a></li>
    <li><a href="#contact">Contact</a></li>
  </ol>
</details>
++++

== About The Project

Swift-GemPDFKit is a (by no means complete) library for parsing, writing, and adding attachments to PDFs. The PDF-parsing and -tokenization depends heavily on https://www.pointfree.co/[Pointfree]'s https://github.com/pointfreeco/swift-parsing[swift-parsing] library.

=== Release Notes

See `link:../ReleaseNotes.md[ReleaseNotes]` for all information regarding the (newest) releases.

== Getting Started

You can parse a PDF file and then add attachments to it:

[source,swift]
----
include::{testDir}/GemPDFKitTests/PDFDocumentAppendTests.swift[tags=parseAndAttachToPdf,indent=0]
----

You can also extract attachments from a PDF:

[source,swift]
----
include::{testDir}/GemPDFKitTests/PDFDocumentAppendTests.swift[tags=extractAttachmentFromPdf,indent=0]
----

=== Prerequisites

Swift 5.7 or later is required.

=== Installation

Add the package as a dependency in your `Package.swift`:

[source,swift]
----
dependencies: [
    .package(url: "https://github.com/gematik/swift-gempdfkit", from: "1.0.0")
]
----

== Usage

Documentation is available at https://swiftpackageindex.com/gematik/swift-gempdfkit/documentation/.

== License

Copyright 2023-2025 gematik GmbH

Apache License, Version 2.0

See the `link:../LICENSE[LICENSE]` for the specific language governing permissions and limitations under the License

== Additional Notes and Disclaimer from gematik GmbH

. Copyright notice: Each published work result is accompanied by an explicit statement of the license conditions for use. These are regularly typical conditions in connection with open source or free software. Programs described/provided/linked here are free software, unless otherwise stated. 
. Permission notice: Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.. The copyright notice (Item 1) and the permission notice (Item 2) shall be included in all copies or substantial portions of the Software.
.. The software is provided "as is" without warranty of any kind, either express or implied, including, but not limited to, the warranties of fitness for a particular purpose, merchantability, and/or non-infringement. The authors or copyright holders shall not be liable in any manner whatsoever for any damages or other claims arising from, out of or in connection with the software or the use or other dealings with the software, whether in an action of contract, tort, or otherwise.
.. The software is the result of research and development activities, therefore not necessarily quality assured and without the character of a liable product. For this reason, gematik does not provide any support or other user assistance (unless otherwise stated in individual cases and without justification of a legal obligation). Furthermore, there is no claim to further development and adaptation of the results to a more current state of the art.
. Gematik may remove published results temporarily or permanently from the place of publication at any time without prior notice or justification.
. Please note: Parts of this code may have been generated using AI-supported technology. Please take this into account, especially when troubleshooting, for security analyses and possible adjustments.

== Contact

This software is currently being tested to ensure its technical quality and legal compliance. Your feedback is highly valued. 
If you find any issues or have any suggestions or comments, or if you see any other ways in which we can improve, please reach out to: ospo@gematik.de.
